version: '3.8'
services:

  youtrade-keygen:
    image: youtrade-keygen
    restart: on-failure
    networks:
      - youtrade-network
    env_file:
      - ./default.env
    deploy:
      resources:
        reservations:
          memory: 150M
        limits:
          memory: 250M

    command: java --enable-preview -jar -XX:+UseZGC -Xms128m -Xmx128m target/youtrade.cs-keygen-service-1.0.jar youtradeKey

volumes:
  postgres_data:
    external: true

networks:
  youtrade-network:
    external: true