version: '3.8'
services:

  youtrade-keygen:
    image: youtrade-keygen
    restart: on-failure
    networks:
      - youtrade-network
    env_file:
      - ./default.env

    command: java --enable-preview -jar target/youtrade.cs-keygen-service-1.0.jar youtradeKey

volumes:
  postgres_data:
    external: true

networks:
  youtrade-network:
    external: true